apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-postgres-secrets
spec:
  provider: vault
  parameters:
    roleName: "5g-role"
    vaultAddress: "https://vault:8200"
    vaultCACertPath: "/vault/userconfig/vault-server-tls/vault.ca"
    objects: |
      - objectName: "POSTGRES_DB"
        secretPath: "vault/postgres"
        secretKey: "POSTGRES_DB"
      - objectName: "POSTGRES_USER"
        secretPath: "vault/postgres"
        secretKey: "POSTGRES_USER"
      - objectName: "POSTGRES_PASSWORD"
        secretPath: "vault/postgres"
        secretKey: "POSTGRES_PASSWORD"
      - objectName: "DATA_SOURCE_URI"
        secretPath: "vault/postgres"
        secretKey: "DATA_SOURCE_URI"
