apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    type: local
    app: vault
spec:
  storageClassName: vault-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /oam/pvc/vault
